vim.opt.swapfile = false
vim.opt.backup = false
vim.opt.compatible =false
vim.opt.smartindent = true
vim.opt.autoindent = true
vim.opt.modeline = true
vim.opt.expandtab = true
vim.opt.background="dark"
vim.opt.softtabstop=4
vim.opt.tabstop=4
vim.opt.shiftwidth=4
vim.opt.expandtab = true
vim.opt.nu = true
vim.opt.cursorline = true
vim.opt.hidden = true
vim.opt.signcolumn="yes"
vim.opt.termguicolors = true
vim.opt.scrolloff = 8
vim.g.netrw_liststyle=3
vim.g.netrw_banner=0
vim.g.netrw_winsize=25

